### ISSUE TITLE
After implementing AFSwiteToHide, Height for row at indexPath won't be called

### ISSUE THREAD

**Issue by alanfeng99** [appfigures/AFSwipeToHide#4]
Hi Sir,

As title, I can't get the normal tableView delegate to work since tableView.delegate = (id<UITableViewDelegate>)_swipeToHide;

Any way to fix it?

**Comment by oztune** [comment]
Since the tableView won't let you share delegate methods with another object, what you wanna do is implement them within your class (as you usually would), but forward these three methods over to your `AFSwipeToHide` instance: https://github.com/appfigures/AFSwipeToHide/blob/master/Pod/Classes/AFSwipeToHide.m#L103-111
